myName = input("What's your name?: ").capitalize()
favFood = input("What's your favorite food?: ")
favMusic = input("What's your favorite music?: ").capitalize()
myLocation = input("Where do you live?: ").capitalize()
print("Getting to know you!")
print()
print(f"You are {myName}")
print(f"You're probably hungry for {favFood}")
print(f"and you're definitely getting your groove on to {favMusic}")
print(f"living in the amazing {myLocation}")
